### ISSUE TITLE
How to properly install chipsequtil

### ISSUE THREAD

**Issue by alexlenail** [fraenkel-lab/chipsequtil#1]
Hi Adam, 

I'm trying to get `map_peaks_to_known_genes` onto [galaxy](https://galaxyproject.org/) for Fraenkel's lab. That requires that I get the tool into one of galaxy's "tool sheds" which requires that I write up some xml describing the inputs and outputs of the program. There exists a repository called [`gxargparse`](https://github.com/erasche/gxargparse) which I think might be a nice shortcut for this. I've installed it and chipsequtil in a vitualenv, and based on what I can tell, I now need to run:

`python map_peaks_to_known_genes.py --generate-galaxy-xml`

But when I do, I get:

`ImportError: No module named chipsequtil`

even though I thought I had installed everything properly. Let me know if I'm missing anything or misunderstanding anything greatly. It would be much appreciated!

**Comment by adamlabadorf** [comment]
Hi,

The error means that the PYTHONPATH variable of the environment calling the python script doesn't contain the directory where it was installed. This might have something to do with the virtualenv, but I don't have any recent experiences with galaxy to know how to troubleshoot. Did you provide a --prefix argument to the setup.py command? The first thing to do is check what is in your PYTHONPATH environment variable. Is the virtualenv you installed the package into properly activated?

Separately - all of the scripts use optparse, and not the more recent argparse. Unless you have ported it yourself, I don't think the gxargparse module will work for you as expected since it overrides argparse (unless it also overrides optparse and doesn't say so). Also, from the gxargparse, I noticed the expected argument for generating the xml is --generate_galaxy_xml, not --generate-galaxy-xml.

**Comment by zfrenchee** [comment]
Hi Adam, 
I managed to get the generate_galaxy_xml to work.
